### PR TITLE
README: update badges

### PR DESCRIPTION
**Pull request by josephholsten**
### Description

* change build status badge from travis to circleci
* remove license badge

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by flaccid** [comment]
User sees straight up at the top visually what the license is :)

**Comment by damacus** [comment]
Honestly just seems like more cruft to maintain in this case. :-1:

**Comment by flaccid** [comment]
Convenience at its worst :)

**Comment by josephholsten** [comment]
I convinced myself that it wasn't valuable because github shows the license above the fold on the github repo page.

I don't think other readers of the README need to know unless they are going to contribute. And the only other situation where a contributor will see this will be while editing the readme in a text editor, and a literal `[License](https://www.apache.org/licenses/LICENSE-2.0)` isn't exactly the most readable way to describe the license in that context.

**Pull request merged**
