### PR TITLE
Merge boundless notions user resources

### PR DESCRIPTION
**Pull request by wolf31o2**
### Description

Creates a new resource, `openvpn_user` which captures the code from the `users` recipe. This was taken from a fork which I happen to consume in a wrapper, and I'd much rather pull this from Supermarket in the long run, so merging it and submitting it.

### Issues Resolved

None that I am aware of...

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by wolf31o2** [comment]
I've rebased this.

**Comment by damacus** [comment]
This looks great, if you know any way of testing this. 

I would really appreciate if you could add some tests. I'll merge this in as soon as we've got a basic test suite for these new resources 👍

**Comment by wolf31o2** [comment]
So... I switched the `user` cookbook to use the resource (duh) and that tests the `openvpn_user_bundle` resource.

```
Profile: tests from {:path=>"/Users/cgianelloni/Repos/forks/openvpn_cookbook/test/integration/server_verification"} (tests from {:path=>".Users.cgianelloni.Repos.forks.openvpn_cookbook.test.integration.server_verification"})
Version: (not specified)
Target:  docker://427605389c09940a924b3f06c060ed82e89f6ae0b510cd907c0ac496c41c6e9d

  File /etc/openvpn/easy-rsa/Rakefile
     ✔  #content should include "remote-cert-tls server"
  File /etc/openvpn/keys/vpn-prod-vpn_user.conf
     ✔  #content should include "remote-cert-tls server"
  File /etc/openvpn/keys/vpn-prod-vpn_user.ovpn
     ✔  #content should include "remote-cert-tls server"

Test Summary: 3 successful, 0 failures, 0 skipped
       Finished verifying <server-verification-ubuntu-1604> (0m0.55s).
-----> Kitchen is finished. (4m18.60s)
```

The inline resource needs an existing CA set.

**Comment by damacus** [comment]
Awesome!
 I think `The inline resource needs an existing CA set.` is probably out of scope of this PR. But I'd really appreciate a PR to make sure that bit isn't broken by any future changes. 

We have two choices, split the resources into two PRs and ship the tested on right away. Wait on the second resource to be tested.

In the future we'll be moving to a Dangerfile https://github.com/danger/danger so I can automate my words ;)

**Comment by wolf31o2** [comment]
Hrrrmn... OK. Let me revisit this and see what I can come up with. Originally, I was just submitting work that was done for my company back to the community. I think I'm going to revisit the resources and merge them into a single `user` resource, with different parameters, since they're very similar. It'll also DRY up the code a bit.

**Comment by jeffbyrnes** [comment]
@wolf31o2 ooh, a single `openvpn_user` sounds fantastic.

That said, perhaps in an effort to get this shipped & the improvements it already offers out the door, following up on @damacus’ suggestion seems reasonable.

Depends on how quickly you think you can get it out the door, I think! I’m gonna take a look at what adding the “inline resource CA set” requires as well, since I’m actively dealing with VPN things for my company.

**Comment by wolf31o2** [comment]
I'm introducing a `use_databag` attribute, when set to false it'll create a single `client` (well, `node['openvpn']['client_cn']`) user. Otherwise, behavior remains the same as currently. This will allow testing both bundle and inline.

**Comment by damacus** [comment]
@wolf31o2 give me a day or two I may have congeneric user code for us to work with as I want to add some user removal support too. 👍

**Comment by jeffbyrnes** [comment]
@wolf31o2 the last rebase seems to have gone pear-shaped. Once @damacus sorts out what they’re working on, mind rebasing this again?

I’m also happy to run with it & take care of that if you’re time-constrained.

**Comment by wolf31o2** [comment]
So my last rebase was against my fork's master, not `upstream/master`... my bad. Rebased again, added tests, and added remove support.

**Comment by wolf31o2** [comment]
Kitchen:
```
$ kitchen verify verif
-----> Starting Kitchen (v1.20.0)
-----> Verifying <server-verification-ubuntu-1604>...
       Loaded tests from {:path=>".Users.cgianelloni.Repos.forks.openvpn_cookbook.test.integration.server_verification"}

Profile: tests from {:path=>"/Users/cgianelloni/Repos/forks/openvpn_cookbook/test/integration/server_verification"} (tests from {:path=>".Users.cgianelloni.Repos.forks.openvpn_cookbook.test.integration.server_verification"})
Version: (not specified)
Target:  docker://5011a67c6d7084f5dcff3eba8465f4ac0b08d5d16cac4c2759a390ff0ada5b2c

  File /etc/openvpn/easy-rsa/Rakefile
     ✔  #content should include "remote-cert-tls server"
  File /etc/openvpn/keys/vpn-prod-vpn_user.conf
     ✔  #content should include "remote-cert-tls server"
  File /etc/openvpn/keys/vpn-prod-vpn_user.ovpn
     ✔  #content should include "remote-cert-tls server"

Test Summary: 3 successful, 0 failures, 0 skipped
       Finished verifying <server-verification-ubuntu-1604> (0m0.57s).
-----> Verifying <server-verify-no-databag-ubuntu-1604>...
       Loaded tests from {:path=>".Users.cgianelloni.Repos.forks.openvpn_cookbook.test.integration.server_verify_no_databag"}

Profile: tests from {:path=>"/Users/cgianelloni/Repos/forks/openvpn_cookbook/test/integration/server_verify_no_databag"} (tests from {:path=>".Users.cgianelloni.Repos.forks.openvpn_cookbook.test.integration.server_verify_no_databag"})
Version: (not specified)
Target:  docker://fdedcaa5a2d705ce77f100b19fe4f8a1f96a8e8e054e09e4fe26359fd911fd7e

  File /etc/openvpn/easy-rsa/Rakefile
     ✔  #content should include "remote-cert-tls server"
  File /etc/openvpn/keys/vpn-prod-client.ovpn
     ✔  #content should include "client"
     ✔  #content should include "<ca>"
     ✔  #content should include "<cert>"
     ✔  #content should include "<key>"

Test Summary: 5 successful, 0 failures, 0 skipped
       Finished verifying <server-verify-no-databag-ubuntu-1604> (0m0.41s).
-----> Kitchen is finished. (0m3.29s)
```

**Comment by jeffbyrnes** [comment]
@wolf31o2 oh snap! Thanks so much for that.

**Comment by damacus** [comment]
This is on my todo list now 👍

**Pull request merged**
