### PR TITLE
Clean up testing

### PR DESCRIPTION
**Pull request by jeffbyrnes**
### Description

Cleans, DRYs, and updates various elements of testings & documentation.

### Issues Resolved

Takes over for and closes #115 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by damacus** [comment]
There are a few platforms dropped here that I'd like to add back in at a later date. 

Thanks for working on this one 👍

**Comment by damacus** [comment]
I'm totally onboard with this. The release hasn't happened for 4 years!

**Comment by damacus** [comment]
On a completely different note, would  you like to become a fully credited contributor to sous-chefs? You look like you know what you're doing.

**Comment by jeffbyrnes** [comment]
@damacus I’d happily accept contributor status. I’ll almost certainly be using this cookbook for the foreseeable future (going on two jobs that I’ve used it, or a fork of it).

**Comment by jeffbyrnes** [comment]
And, not to nitpick, but if you do decide to grant that, would you be willing to also grant maintainer on the Supermarket? Then I’d be able to actually ship releases.

Totally OK if you’d like to be the gatekeeper for those, however!

**Comment by damacus** [comment]
totally, I'd have to run it past the current crew first (/cc @flaccid)

If  you want to, 

1. Make a PR in the [terraform-github-org](https://github.com/sous-chefs/terraform-github-org) in the [OpenVPN repo](https://github.com/sous-chefs/terraform-github-org/blob/master/openvpn.tf). 

2. Throw yourself in the [org_membership file](https://github.com/sous-chefs/terraform-github-org/blob/master/modules/org_membership/main.tf)
3. ? 
4. Profit

**Pull request merged**
