### PR TITLE
Initial support for revoking user certs

### PR DESCRIPTION
**Pull request by georgiou**

### CODE REVIEW

**Comment by flaccid** [comment]
@jtimberman appreciate a review if possible please.

**Comment by jtimberman** [comment]
Hey @flaccid, I don't work on cookbooks regularly and don't have cycles for code review. If you don't have cycles either, perhaps this cookbook should be transferred to sous-chefs (formerly chef-brigade)?

http://sous-chefs.org/

**Comment by tas50** [comment]
We'd love to get this one into sous chefs. It's an important cookbook for the community and it would help get additional eyes on the code.

**Comment by flaccid** [comment]
@jtimberman time is not in issue, was just after a good pair of different eyes and you're in this org still. @tas50 happy to transfer it to sous-chefs if I can be added to the org; failing that sous-chefs are welcome to just help right here :)

**Comment by damacus** [comment]
I would prefer if we could use a custom-resource for users rather than using/adding a data_bag.

**Pull request merged**
