### PR TITLE
Add server-bridge support in conf

### PR DESCRIPTION
**Pull request by paulpalamarchuk**
### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by damacus** [comment]
Thanks! 

LGTM 👍 

@flaccid over to you :)

**Comment by flaccid** [comment]
@damacus looks potentially fine, but can someone fix the failed travis stuff related to chef delivery (who ever added that in)?

**Comment by damacus** [comment]
Don't mind doing that if I get a chance this week 

@paulpalamarchuk do you want to give it a go? Drop me a line on sous-chefs slack if you need a hand!

**Comment by MarkGibbons** [comment]
Working on the Travis errors.

**Comment by damacus** [comment]
Merging and creating issues for the foodcritic failures.

**Pull request merged**
