### PR TITLE
Occasionaly refresh the CRL

### PR DESCRIPTION
**Pull request by stefanor**
### Description

Refresh the CRL once every 15 days, by default, or after creating/revoking a certificate.

And tweak the format of the CRL, while we're here.

### Issues Resolved

* Currently, the CRL is configured to expire after 30 days. And nothing will refresh it. So the VPN server isn't useful after 30 days.
* Don't use MD5 for the CRL, use the configured hash (presumably SHA-256).
* Use CRL format 2.

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by scopenco** [comment]
For me it doesn't revoke anything at all. Seems the execute is wrong from the beginning. It works when gencrl is like 
```
          "-keyfile #{key_dir}/ca.key " \
          "-cert #{key_dir}/ca.crt " \
```
not server.

**Comment by stefanor** [comment]
You're right, that was totally broken :+1:

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by stefanor** [comment]
Tests are passing everywhere they do on master.

**Comment by damacus** [comment]
Thanks this is a great contribution. If you have time, I/we would really like it if someone could help maintain/fix the minor CI bugs in this cookbook

**Pull request merged**
