### PR TITLE
Add server verification method to client's Rakefile template

### PR DESCRIPTION
**Pull request by szymonpk**
Without any server verification method newer client versions are sending a warning. Possible fixes are [described in documentation](http://openvpn.net/howto.html#mitm). 

    Wed Jun  7 12:40:34 2017 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.

Setting server verification method is optional and it does not break current functionality.

### CODE REVIEW

**Comment by damacus** [comment]
@szymonpk worth throwing in some tests for this?

**Comment by szymonpk** [comment]
I was not sure about testing this, it may lengthen `kitchen converge` run, if we will test this on all images. I was thinking about separate suite with single image, what do you think @damacus? Will it be enough? Or I can extend default suite.

**Comment by damacus** [comment]
We've just included a single platform on single configs in haproxy for this exact reason. If it's not platform dependant this seems like 'good enough'

https://github.com/sous-chefs/haproxy/blob/master/.kitchen.yml#L64

**Comment by szymonpk** [comment]
@damacus I have added small test suite.

**Pull request merged**
