### PR TITLE
Add integration tests using CircleCI

### PR DESCRIPTION
**Pull request by jeffbyrnes**
### Description

Takes over for #140, replicating its efforts against master (didn’t want to go around rebasing someone else’s branch).

### Issues Resolved

Closes #140 

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by josephholsten** [comment]
so... close...

**Comment by josephholsten** [comment]
Error from the failing test for server-fedora-latest:
```
Recipe: openvpn::service
  * link[/etc/systemd/system/multi-user.target.wants/openvpn@server.service] action create
    - create symlink at /etc/systemd/system/multi-user.target.wants/openvpn@server.service to /usr/lib/systemd/system/openvpn@.service
  * service[openvpn] action enable
    
    ================================================================================
    Error executing action `enable` on resource 'service[openvpn]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /usr/bin/systemctl --system enable openvpn@server.service ----
    STDOUT: 
    STDERR: Failed to enable unit: Unit file openvpn@server.service does not exist.
    ---- End output of /usr/bin/systemctl --system enable openvpn@server.service ----
    Ran /usr/bin/systemctl --system enable openvpn@server.service returned 1
    
    Resource Declaration:
    ---------------------
    # In /opt/kitchen/cache/cookbooks/openvpn/recipes/service.rb
    
     61: service 'openvpn' do
     62:   service_name service_name
     63:   action [:enable, :start]
     64: end
    
    Compiled Resource:
    ------------------
    # Declared in /opt/kitchen/cache/cookbooks/openvpn/recipes/service.rb:61:in `from_file'
    
    service("openvpn") do
      action [:enable, :start]
      default_guard_interpreter :default
      declared_type :service
      cookbook_name "openvpn"
      recipe_name "service"
      service_name "openvpn@server.service"
    end
    
    System Info:
    ------------
    chef_version=15.0.158
    platform=fedora
    platform_version=29
    ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
    program_name=/opt/chef/embedded/bin/chef-client
    executable=/opt/chef/embedded/bin/chef-client
    
  * service[openvpn] action restart
    
    ================================================================================
    Error executing action `restart` on resource 'service[openvpn]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '5'
    ---- Begin output of /usr/bin/systemctl --system restart openvpn@server.service ----
    STDOUT: 
    STDERR: Failed to restart openvpn@server.service: Unit openvpn@server.service not found.
    ---- End output of /usr/bin/systemctl --system restart openvpn@server.service ----
    Ran /usr/bin/systemctl --system restart openvpn@server.service returned 5
    
    Resource Declaration:
    ---------------------
    # In /opt/kitchen/cache/cookbooks/openvpn/recipes/service.rb
    
     61: service 'openvpn' do
     62:   service_name service_name
     63:   action [:enable, :start]
     64: end
    
    Compiled Resource:
    ------------------
    # Declared in /opt/kitchen/cache/cookbooks/openvpn/recipes/service.rb:61:in `from_file'
    
    service("openvpn") do
      action [:enable, :start]
      default_guard_interpreter :default
      declared_type :service
      cookbook_name "openvpn"
      recipe_name "service"
      service_name "openvpn@server.service"
    end
    
    System Info:
    ------------
    chef_version=15.0.158
    platform=fedora
    platform_version=29
    ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
    program_name=/opt/chef/embedded/bin/chef-client
    executable=/opt/chef/embedded/bin/chef-client
    

Running handlers:
[2019-02-12T22:54:24+00:00] ERROR: Running exception handlers
Running handlers complete
[2019-02-12T22:54:24+00:00] ERROR: Exception handlers complete
Chef Client failed. 26 resources updated in 04 minutes 03 seconds
[2019-02-12T22:54:24+00:00] FATAL: Stacktrace dumped to /opt/kitchen/cache/chef-stacktrace.out
[2019-02-12T22:54:24+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-02-12T22:54:24+00:00] FATAL: Chef::Exceptions::MultipleFailures: Multiple failures occurred:
* Mixlib::ShellOut::ShellCommandFailed occurred in chef run: service[openvpn] (openvpn::service line 61) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/systemctl --system enable openvpn@server.service ----
STDOUT: 
STDERR: Failed to enable unit: Unit file openvpn@server.service does not exist.
---- End output of /usr/bin/systemctl --system enable openvpn@server.service ----
Ran /usr/bin/systemctl --system enable openvpn@server.service returned 1
* Mixlib::ShellOut::ShellCommandFailed occurred in delayed notification: service[openvpn] (openvpn::service line 61) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '5'
---- Begin output of /usr/bin/systemctl --system restart openvpn@server.service ----
STDOUT: 
STDERR: Failed to restart openvpn@server.service: Unit openvpn@server.service not found.
---- End output of /usr/bin/systemctl --system restart openvpn@server.service ----
Ran /usr/bin/systemctl --system restart openvpn@server.service returned 5
```

**Comment by damacus** [comment]
Honestly I think we can remove Fedora from *all* test suites. 

It's close to RHEL flavours, but some bugs are not fixed until it's put into or about to be put into RedHat.

**Comment by damacus** [comment]
I'm going to merge this in, and make some changes on top. But this is really good thank you! 👍

**Pull request merged**
