### PR TITLE
Bit scrappy and needs some tests

### LINKED ISSUE #55: Interest in handling user removal & suspension?
Looking through the code/doc, I don't see a solution for:
- removing credentials for users with "remove" action
- suspending credentials for users with "lock" action

Let me know if I just missed it or if folks are handling in a different manner.  If not, is there any interest in supporting either of these use cases?  If so, I can do my work in this cookbook and submit as PR.  Otherwise, will just handle via wrapper.  

Cheers,

Todd

### PR DESCRIPTION
**Pull request by damacus**
### Description

User removal support

### Issues Resolved

 #55 

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by tas50** [comment]
You have a ruby syntax error @damacus

**Comment by jeffbyrnes** [comment]
Seems like this needs a rebase. Or perhaps it has been superseded by other efforts?

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add labels to this Pull Request</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/openvpn/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Xorima** [comment]
Hey, 

Thank you for the PR. We are closing due to inactivity. 
If you feel this feature should be merged in, please reopen and rebase as your contributions are always welcome.

Sous Chefs

**Pull request closed without merging**
