### PR TITLE
Add server bridge support

### PR DESCRIPTION
**Pull request by MarkGibbons**
### Description

Fix metadata issues with the pull request from paulpaamarchuk

### Issues Resolved

None

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by MarkGibbons** [comment]
Attributes in a metadata file - made sense to me to remove them.   They aren't a valid part of the file anymore.

From https://docs.chef.io/config_rb_metadata.html
attribute
Deprecated in Chef Client 13.0, pending removal in 14.0.

Warning
attribute in cookbook configuration is deprecated and will be removed. attribute often requires frequent updating in the code, in the README.md file, and in the metadata, which may lead to extensive technical debt. When used, the current version of foodcritic will throw a warning.

**Comment by flaccid** [comment]
Has never made sense to me, thus why I do `foodcritic -t ~FC072`.

**Comment by MarkGibbons** [comment]
Won't the metadata attributes cause an error in chef 14 client?

**Comment by tas50** [comment]
They won't cause an error. They'll pretty much continue to get ignored. They've never done anything, but they should get removed.

**Comment by flaccid** [comment]
They have historically helped system integrators that build interfaces into using cookbooks.

**Comment by MarkGibbons** [comment]
Attributes back in and FC072 bypassed.  Author's choice.  That will teach me not to procrastinate by working on an OSS project.

Cheers,
   Mark

**Comment by damacus** [comment]
Resolves #120

**Pull request merged**
